"""empty message

Revision ID: 220a6ac3acd4
Revises: b52800c83707
Create Date: 2025-06-11 15:54:06.067701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '220a6ac3acd4'
down_revision = 'b52800c83707'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('segment', schema=None) as batch_op:
        batch_op.create_index('segment_dataset_id_idx', ['dataset_id'], unique=False)
        batch_op.create_index('segment_document_id_idx', ['document_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('segment', schema=None) as batch_op:
        batch_op.drop_index('segment_document_id_idx')
        batch_op.drop_index('segment_dataset_id_idx')

    # ### end Alembic commands ###
