"""empty message

Revision ID: 352fdd9a242c
Revises: 09b68127ca41
Create Date: 2025-03-26 22:11:14.735058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '352fdd9a242c'
down_revision = '09b68127ca41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.alter_column('account_id',
               existing_type=sa.UUID(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.alter_column('account_id',
               existing_type=sa.UUID(),
               nullable=False)

    # ### end Alembic commands ###
