"""add suggested_questions to message

Revision ID: 617bb673dc4f
Revises: 2ba48ef17189
Create Date: 2026-02-27 19:44:16.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSONB


# revision identifiers, used by Alembic.
revision = '617bb673dc4f'
down_revision = '2ba48ef17189'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('suggested_questions', JSONB, nullable=False, server_default=sa.text("'[]'::jsonb")))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('suggested_questions')

    # ### end Alembic commands ###
