"""add public sharing fields to app and workflow

Revision ID: 918e435d1019
Revises: 8042a1160a4d
Create Date: 2026-02-28 22:35:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '918e435d1019'
down_revision = '8042a1160a4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. 为 app 表添加公共共享字段
    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), nullable=False, server_default=sa.text('false')))
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=False, server_default=sa.text("'general'::character varying")))
        batch_op.add_column(sa.Column('published_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('view_count', sa.Integer(), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('like_count', sa.Integer(), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('fork_count', sa.Integer(), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('original_app_id', sa.UUID(), nullable=True))
        batch_op.create_index('app_is_public_idx', ['is_public'])
        batch_op.create_index('app_category_idx', ['category'])
        batch_op.create_index('app_like_count_idx', ['like_count'])

    # 2. 为 workflow 表添加公共共享字段
    with op.batch_alter_table('workflow', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), nullable=False, server_default=sa.text('false')))
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=False, server_default=sa.text("'general'::character varying")))
        batch_op.add_column(sa.Column('view_count', sa.Integer(), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('like_count', sa.Integer(), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('fork_count', sa.Integer(), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('original_workflow_id', sa.UUID(), nullable=True))
        batch_op.create_index('workflow_is_public_idx', ['is_public'])
        batch_op.create_index('workflow_category_idx', ['category'])
        batch_op.create_index('workflow_like_count_idx', ['like_count'])

    # 3. 创建 app_like 表 (用户点赞应用)
    op.create_table('app_like',
        sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
        sa.Column('app_id', sa.UUID(), nullable=False),
        sa.Column('account_id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
        sa.PrimaryKeyConstraint('id', name='pk_app_like_id'),
        sa.UniqueConstraint('app_id', 'account_id', name='uq_app_like_app_account')
    )
    op.create_index('app_like_app_id_idx', 'app_like', ['app_id'])
    op.create_index('app_like_account_id_idx', 'app_like', ['account_id'])

    # 4. 创建 app_favorite 表 (用户收藏应用)
    op.create_table('app_favorite',
        sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
        sa.Column('app_id', sa.UUID(), nullable=False),
        sa.Column('account_id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
        sa.PrimaryKeyConstraint('id', name='pk_app_favorite_id'),
        sa.UniqueConstraint('app_id', 'account_id', name='uq_app_favorite_app_account')
    )
    op.create_index('app_favorite_app_id_idx', 'app_favorite', ['app_id'])
    op.create_index('app_favorite_account_id_idx', 'app_favorite', ['account_id'])

    # 5. 创建 workflow_like 表 (用户点赞工作流)
    op.create_table('workflow_like',
        sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
        sa.Column('workflow_id', sa.UUID(), nullable=False),
        sa.Column('account_id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
        sa.PrimaryKeyConstraint('id', name='pk_workflow_like_id'),
        sa.UniqueConstraint('workflow_id', 'account_id', name='uq_workflow_like_workflow_account')
    )
    op.create_index('workflow_like_workflow_id_idx', 'workflow_like', ['workflow_id'])
    op.create_index('workflow_like_account_id_idx', 'workflow_like', ['account_id'])

    # 6. 创建 workflow_favorite 表 (用户收藏工作流)
    op.create_table('workflow_favorite',
        sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
        sa.Column('workflow_id', sa.UUID(), nullable=False),
        sa.Column('account_id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
        sa.PrimaryKeyConstraint('id', name='pk_workflow_favorite_id'),
        sa.UniqueConstraint('workflow_id', 'account_id', name='uq_workflow_favorite_workflow_account')
    )
    op.create_index('workflow_favorite_workflow_id_idx', 'workflow_favorite', ['workflow_id'])
    op.create_index('workflow_favorite_account_id_idx', 'workflow_favorite', ['account_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # 删除表
    op.drop_table('workflow_favorite')
    op.drop_table('workflow_like')
    op.drop_table('app_favorite')
    op.drop_table('app_like')

    # 删除 workflow 表字段
    with op.batch_alter_table('workflow', schema=None) as batch_op:
        batch_op.drop_index('workflow_like_count_idx')
        batch_op.drop_index('workflow_category_idx')
        batch_op.drop_index('workflow_is_public_idx')
        batch_op.drop_column('original_workflow_id')
        batch_op.drop_column('fork_count')
        batch_op.drop_column('like_count')
        batch_op.drop_column('view_count')
        batch_op.drop_column('category')
        batch_op.drop_column('is_public')

    # 删除 app 表字段
    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.drop_index('app_like_count_idx')
        batch_op.drop_index('app_category_idx')
        batch_op.drop_index('app_is_public_idx')
        batch_op.drop_column('original_app_id')
        batch_op.drop_column('fork_count')
        batch_op.drop_column('like_count')
        batch_op.drop_column('view_count')
        batch_op.drop_column('published_at')
        batch_op.drop_column('category')
        batch_op.drop_column('is_public')

    # ### end Alembic commands ###
