"""replace category with tags for app and workflow

Revision ID: a1b2c3d4e5f6
Revises: 918e435d1019
Create Date: 2026-03-19 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = '918e435d1019'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. 为 app 表添加 tags 字段
    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', postgresql.JSONB(), nullable=False, server_default=sa.text("'[]'::jsonb")))
        batch_op.create_index('app_tags_idx', ['tags'], postgresql_using='gin')
        # 删除 category 字段和相关索引
        batch_op.drop_index('app_category_idx')
        batch_op.drop_column('category')

    # 2. 为 workflow 表添加 tags 字段
    with op.batch_alter_table('workflow', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', postgresql.JSONB(), nullable=False, server_default=sa.text("'[]'::jsonb")))
        batch_op.create_index('workflow_tags_idx', ['tags'], postgresql_using='gin')
        # 删除 category 字段和相关索引
        batch_op.drop_index('workflow_category_idx')
        batch_op.drop_column('category')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. 为 workflow 表恢复 category 字段
    with op.batch_alter_table('workflow', schema=None) as batch_op:
        batch_op.drop_index('workflow_tags_idx')
        batch_op.drop_column('tags')
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=False, server_default=sa.text("'general'::character varying")))
        batch_op.create_index('workflow_category_idx', ['category'])

    # 2. 为 app 表恢复 category 字段
    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.drop_index('app_tags_idx')
        batch_op.drop_column('tags')
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=False, server_default=sa.text("'general'::character varying")))
        batch_op.create_index('app_category_idx', ['category'])

    # ### end Alembic commands ###
