"""empty message

Revision ID: dbbb4f3fe0c7
Revises: 8042a1160a4d
Create Date: 2025-06-05 21:30:34.578939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbbb4f3fe0c7'
down_revision = '8042a1160a4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assistant_agent_conversation_id', sa.UUID(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_column('assistant_agent_conversation_id')

    # ### end Alembic commands ###
