from __future__ import annotations

from collections import defaultdict


def _methods(rule):
    return {m for m in rule.methods if m not in {"HEAD", "OPTIONS"}}


class TestRouterFullMatrix:
    """路由全量矩阵契约测试，覆盖路径、HTTP 方法与蓝图边界。"""

    def test_should_match_full_path_method_matrix(self, app):
        route_methods = defaultdict(set)
        for rule in app.url_map.iter_rules():
            if rule.endpoint == "static":
                continue
            route_methods[rule.rule].update(_methods(rule))

        expected = {
            '/account': {'GET'},
            '/account/avatar': {'POST'},
            '/account/email': {'POST'},
            '/account/email/send-code': {'POST'},
            '/account/login-history': {'GET'},
            '/account/name': {'POST'},
            '/account/oauth/<string:provider_name>/unbind': {'POST'},
            '/account/password': {'POST'},
            '/account/sessions': {'GET'},
            '/account/sessions/<uuid:session_id>/revoke': {'POST'},
            '/account/sessions/revoke-others': {'POST'},
            '/ai/chat': {'POST'},
            '/ai/mcp-schema-chat': {'POST'},
            '/ai/openapi-schema-chat': {'POST'},
            '/ai/optimize-prompt': {'POST'},
            '/ai/suggested-questions': {'POST'},
            '/analysis/<uuid:app_id>': {'GET'},
            '/admin/admin-users': {'GET', 'POST'},
            '/admin/admin-users/<uuid:admin_id>': {'GET', 'PATCH'},
            '/admin/admin-users/<uuid:admin_id>/disable': {'POST'},
            '/admin/users': {'GET'},
            '/admin/users/<uuid:account_id>': {'GET'},
            '/admin/users/<uuid:account_id>/disable': {'POST'},
            '/admin/users/<uuid:account_id>/enable': {'POST'},
            '/admin/users/<uuid:account_id>/sessions/revoke': {'POST'},
            '/admin/users/<uuid:account_id>/app-assignments': {'GET', 'POST'},
            '/admin/users/<uuid:account_id>/app-assignments/<uuid:assignment_id>/revoke': {'POST'},
            '/admin/apps': {'GET'},
            '/admin/apps/<uuid:app_id>': {'GET', 'PATCH'},
            '/admin/apps/<uuid:app_id>/offline': {'POST'},
            '/admin/audit-logs': {'GET'},
            '/admin/routing-logs': {'GET'},
            '/admin/orchestration-flags': {'GET'},
            '/admin/orchestration-flags/<string:code>': {'POST'},
            '/admin/orchestration-release-check': {'GET'},
            '/admin/auth/login': {'POST'},
            '/admin/auth/logout': {'POST'},
            '/admin/auth/me': {'GET'},
            '/admin/auth/password': {'POST'},
            '/admin/datasets': {'GET'},
            '/admin/mcp': {'GET'},
            '/admin/permissions': {'GET'},
            '/admin/plans': {'GET', 'POST'},
            '/admin/plans/<uuid:plan_id>': {'GET', 'POST'},
            '/admin/plans/<uuid:plan_id>/status': {'POST'},
            '/admin/redeem-code-batches': {'GET', 'POST'},
            '/admin/redeem-code-batches/<uuid:batch_id>/disable': {'POST'},
            '/admin/redeem-codes': {'GET'},
            '/admin/redeem-codes/<uuid:code_id>/disable': {'POST'},
            '/admin/roles': {'GET', 'POST'},
            '/admin/roles/<uuid:role_id>': {'GET', 'PATCH', 'DELETE'},
            '/admin/skills': {'GET'},
            '/admin/tools': {'GET'},
            '/admin/workflows': {'GET'},
            '/admin/workflows/<uuid:workflow_id>': {'GET', 'PATCH'},
            '/admin/workflows/<uuid:workflow_id>/offline': {'POST'},
            '/api-tools': {'GET', 'POST'},
            '/api-tools/<uuid:provider_id>': {'GET', 'POST'},
            '/api-tools/<uuid:provider_id>/delete': {'POST'},
            '/api-tools/<uuid:provider_id>/regenerate-icon': {'POST'},
            '/api-tools/<uuid:provider_id>/tools/<string:tool_name>': {'GET'},
            '/api-tools/generate-icon-preview': {'POST'},
            '/api-tools/validate-openapi-schema': {'POST'},
            '/apps': {'GET', 'POST'},
            '/apps/<uuid:app_id>': {'GET', 'POST'},
            '/apps/<uuid:app_id>/cancel-publish': {'POST'},
            '/apps/<uuid:app_id>/conversations': {'POST'},
            '/apps/<uuid:app_id>/conversations/delete-debug-conversation': {'POST'},
            '/apps/<uuid:app_id>/conversations/messages': {'GET'},
            '/apps/<uuid:app_id>/conversations/tasks/<uuid:task_id>/stop': {'POST'},
            '/apps/<uuid:app_id>/copy': {'POST'},
            '/apps/<uuid:app_id>/delete': {'POST'},
            '/apps/<uuid:app_id>/draft-app-config': {'GET', 'POST'},
            '/apps/<uuid:app_id>/fallback-history': {'POST'},
            '/apps/<uuid:app_id>/publish': {'POST'},
            '/apps/<uuid:app_id>/publish-histories': {'GET'},
            '/apps/<uuid:app_id>/published-config': {'GET'},
            '/apps/<uuid:app_id>/published-config/regenerate-web-app-token': {'POST'},
            '/apps/<uuid:app_id>/prompt-compare/chat': {'POST'},
            '/apps/<uuid:app_id>/prompt-compare/tasks/<uuid:task_id>/stop': {'POST'},
            '/apps/<uuid:app_id>/regenerate-icon': {'POST'},
            '/apps/<uuid:app_id>/share-to-square': {'POST'},
            '/apps/<uuid:app_id>/summary': {'GET', 'POST'},
            '/apps/<uuid:app_id>/unshare-from-square': {'POST'},
            '/apps/<uuid:app_id>/versions': {'GET'},
            '/apps/generate-icon-preview': {'POST'},
            '/assistant-agent/chat': {'POST'},
            '/assistant-agent/chat/<uuid:task_id>/stop': {'POST'},
            '/assistant-agent/capabilities': {'GET'},
            '/assistant-agent/conversations': {'GET'},
            '/assistant-agent/delete-conversation': {'POST'},
            '/assistant-agent/introduction': {'POST'},
            '/assistant-agent/messages': {'GET'},
            '/audio/audio-to-text': {'POST'},
            '/audio/message-to-audio': {'POST'},
            '/audio/text-to-audio': {'POST'},
            '/auth/logout': {'POST'},
            '/auth/login-challenge/resend': {'POST'},
            '/auth/login-challenge/verify': {'POST'},
            '/auth/password-login': {'POST'},
            '/auth/register/prepare': {'POST'},
            '/auth/register/verify': {'POST'},
            '/auth/reset-password': {'POST'},
            '/auth/send-reset-code': {'POST'},
            '/builtin-tools': {'GET'},
            '/builtin-tools/<string:provider_name>/icon': {'GET'},
            '/builtin-tools/<string:provider_name>/tools/<string:tool_name>': {'GET'},
            '/builtin-tools/categories': {'GET'},
            '/conversations/<uuid:conversation_id>/delete': {'POST'},
            '/conversations/<uuid:conversation_id>/is-pinned': {'POST'},
            '/conversations/<uuid:conversation_id>/messages': {'GET'},
            '/conversations/<uuid:conversation_id>/messages/<uuid:message_id>': {'POST'},
            '/conversations/<uuid:conversation_id>/messages/<uuid:message_id>/delete': {'POST'},
            '/conversations/<uuid:conversation_id>/name': {'GET', 'POST'},
            '/conversations/recent': {'GET'},
            '/conversations/search': {'GET'},
            '/datasets': {'GET', 'POST'},
            '/datasets/<uuid:dataset_id>': {'GET', 'POST'},
            '/datasets/<uuid:dataset_id>/delete': {'POST'},
            '/datasets/<uuid:dataset_id>/documents': {'GET', 'POST'},
            '/datasets/<uuid:dataset_id>/documents/<uuid:document_id>': {'GET'},
            '/datasets/<uuid:dataset_id>/documents/<uuid:document_id>/delete': {'POST'},
            '/datasets/<uuid:dataset_id>/documents/<uuid:document_id>/enabled': {'POST'},
            '/datasets/<uuid:dataset_id>/documents/<uuid:document_id>/name': {'POST'},
            '/datasets/<uuid:dataset_id>/documents/<uuid:document_id>/segments': {'GET', 'POST'},
            '/datasets/<uuid:dataset_id>/documents/<uuid:document_id>/segments/<uuid:segment_id>': {'GET', 'POST'},
            '/datasets/<uuid:dataset_id>/documents/<uuid:document_id>/segments/<uuid:segment_id>/delete': {'POST'},
            '/datasets/<uuid:dataset_id>/documents/<uuid:document_id>/segments/<uuid:segment_id>/enabled': {'POST'},
            '/datasets/<uuid:dataset_id>/documents/batch/<string:batch>': {'GET'},
            '/datasets/<uuid:dataset_id>/hit': {'POST'},
            '/datasets/<uuid:dataset_id>/queries': {'GET'},
            '/datasets/<uuid:dataset_id>/regenerate-icon': {'POST'},
            '/datasets/generate-icon-preview': {'POST'},
            '/external-data-sources': {'POST'},
            '/external-data-sources/<uuid:data_source_id>/sync': {'POST'},
            '/health': {'GET'},
            '/healthz': {'GET'},
            '/home/intent': {'GET'},
            '/language-models': {'GET'},
            '/language-models/<string:provider_name>/<string:model_name>': {'GET'},
            '/language-models/<string:provider_name>/icon': {'GET'},
            '/membership/redeem-records': {'GET'},
            '/membership/summary': {'GET'},
            '/memory-candidates/<uuid:candidate_id>/confirm': {'POST'},
            '/memory-candidates/<uuid:candidate_id>/ignore': {'POST'},
            '/my/apps': {'GET'},
            '/my/apps/<uuid:app_id>/chat': {'POST'},
            '/mcp-providers': {'GET', 'POST'},
            '/mcp-providers/<uuid:provider_id>': {'GET', 'POST'},
            '/mcp-providers/<uuid:provider_id>/delete': {'POST'},
            '/mcp-providers/<uuid:provider_id>/publish': {'POST'},
            '/mcp-providers/<uuid:provider_id>/regenerate-icon': {'POST'},
            '/mcp-providers/<uuid:provider_id>/unpublish': {'POST'},
            '/mcp-providers/categories': {'GET'},
            '/mcp-providers/generate-icon-preview': {'POST'},
            '/notifications': {'GET'},
            '/notifications/<string:notification_id>': {'DELETE'},
            '/notifications/<string:notification_id>/read': {'POST'},
            '/oauth/<string:provider_name>': {'GET'},
            '/oauth/authorize/<string:provider_name>': {'POST'},
            '/openapi/api-keys': {'GET', 'POST'},
            '/openapi/api-keys/<uuid:api_key_id>': {'POST'},
            '/openapi/api-keys/<uuid:api_key_id>/delete': {'POST'},
            '/openapi/api-keys/<uuid:api_key_id>/is-active': {'POST'},
            '/openapi/chat': {'POST'},
            '/ping': {'GET'},
            '/platform/<uuid:app_id>/wechat-config': {'GET', 'POST'},
            '/public/apps': {'GET'},
            '/public/apps/<string:app_id>': {'GET'},
            '/public/apps/<string:app_id>/a2a/agent-card': {'GET'},
            '/public/apps/<string:app_id>/a2a/conversations/latest': {'GET'},
            '/public/apps/<string:app_id>/a2a/conversations/<string:conversation_id>/messages': {'GET'},
            '/public/apps/<string:app_id>/a2a/messages': {'POST'},
            '/public/apps/<string:app_id>/fork': {'POST'},
            '/public/apps/tags': {'GET'},
            '/public/mcp-providers': {'GET'},
            '/public/mcp-providers/<string:provider_key>': {'GET'},
            '/public/mcp-providers/categories': {'GET'},
            '/public/workflows': {'GET'},
            '/public/workflows/<uuid:workflow_id>': {'GET'},
            '/public/workflows/<uuid:workflow_id>/draft-graph': {'GET'},
            '/public/workflows/<uuid:workflow_id>/fork': {'POST'},
            '/redeem-codes/redeem': {'POST'},
            '/skills': {'GET'},
            '/skills/<uuid:skill_id>': {'GET'},
            '/skills/<uuid:skill_id>/icon': {'GET'},
            '/skills/<uuid:skill_id>/versions': {'GET'},
            '/skills/<uuid:skill_id>/enable': {'POST'},
            '/skills/<uuid:skill_id>/disable': {'POST'},
            '/skills/<uuid:skill_id>/sync': {'POST'},
            '/skills/<uuid:skill_id>/rollback': {'POST'},
            '/skills/categories': {'GET'},
            '/tags': {'GET', 'POST'},
            '/tags/<uuid:tag_id>': {'GET', 'POST'},
            '/tags/<uuid:tag_id>/delete': {'POST'},
            '/tags/dimensions': {'GET'},
            '/tags/hot': {'GET'},
            '/tool-inventory': {'GET'},
            '/tool-confirmations': {'POST'},
            '/tool-confirmations/<uuid:confirmation_id>/cancel': {'POST'},
            '/tool-confirmations/<uuid:confirmation_id>/confirm': {'POST'},
            '/upload-files/file': {'POST'},
            '/upload-files/image': {'POST'},
            '/web-apps/<string:token>': {'GET'},
            '/web-apps/<string:token>/chat': {'POST'},
            '/web-apps/<string:token>/chat/<uuid:task_id>/stop': {'POST'},
            '/web-apps/<string:token>/conversations': {'GET'},
            '/wechat/<uuid:app_id>': {'GET', 'POST'},
            '/workflows': {'GET', 'POST'},
            '/workflows/<uuid:workflow_id>': {'GET', 'POST'},
            '/workflows/<uuid:workflow_id>/cancel-publish': {'POST'},
            '/workflows/<uuid:workflow_id>/debug': {'POST'},
            '/workflows/<uuid:workflow_id>/delete': {'POST'},
            '/workflows/<uuid:workflow_id>/draft-graph': {'GET', 'POST'},
            '/workflows/<uuid:workflow_id>/publish': {'POST'},
            '/workflows/<uuid:workflow_id>/regenerate-icon': {'POST'},
            '/workflows/<uuid:workflow_id>/share': {'POST'},
            '/workflows/<uuid:workflow_id>/share-to-square': {'POST'},
            '/workflows/<uuid:workflow_id>/unshare-from-square': {'POST'},
            '/workflows/generate-icon-preview': {'POST'},
        }

        assert dict(route_methods) == expected

    def test_should_keep_blueprint_and_method_constraints(self, app):
        assert set(app.blueprints.keys()) == {"llmops", "openapi"}

        rules = [rule for rule in app.url_map.iter_rules() if rule.endpoint != "static"]
        by_blueprint = defaultdict(int)
        for rule in rules:
            blueprint_name = rule.endpoint.split(".", 1)[0]
            by_blueprint[blueprint_name] += 1
            assert _methods(rule).issubset({"GET", "POST", "PATCH", "DELETE"})
            assert len(_methods(rule)) >= 1

        assert by_blueprint["openapi"] == 1
        assert by_blueprint["llmops"] == len(rules) - 1
        # 当前系统的接口总量是一个重要契约，避免漏挂导致线上能力消失。
        assert len(rules) == 252
