#!/bin/bash

# GitHub 推送指南
# 由于需要身份验证，请手动执行以下步骤

echo "=========================================="
echo "  GitHub 推送指南"
echo "=========================================="
echo ""
echo "✅ 代码已经提交到本地 Git 仓库！"
echo ""
echo "📋 现在需要推送到 GitHub，请按以下步骤操作："
echo ""
echo "方式 1: 使用 Personal Access Token（推荐）"
echo "----------------------------------------"
echo "1. 生成 GitHub Token:"
echo "   访问: https://github.com/settings/tokens"
echo "   点击 'Generate new token' → 'Generate new token (classic)'"
echo "   勾选权限: repo (完整仓库访问)"
echo "   生成并复制 Token"
echo ""
echo "2. 推送代码:"
echo "   git push -u origin main"
echo ""
echo "3. 输入凭证:"
echo "   Username: Haohao-end"
echo "   Password: [粘贴你的 Token]"
echo ""
echo ""
echo "方式 2: 使用 SSH（更安全）"
echo "----------------------------------------"
echo "1. 生成 SSH 密钥:"
echo "   ssh-keygen -t ed25519 -C '2227625024@qq.com'"
echo ""
echo "2. 添加 SSH 密钥到 GitHub:"
echo "   cat ~/.ssh/id_ed25519.pub"
echo "   复制输出，访问: https://github.com/settings/keys"
echo "   点击 'New SSH key'，粘贴密钥"
echo ""
echo "3. 修改远程仓库 URL:"
echo "   git remote set-url origin git@github.com:Haohao-end/openagent.git"
echo ""
echo "4. 推送代码:"
echo "   git push -u origin main"
echo ""
echo ""
echo "方式 3: 使用 GitHub CLI（最简单）"
echo "----------------------------------------"
echo "1. 安装 GitHub CLI:"
echo "   sudo apt install gh"
echo ""
echo "2. 登录 GitHub:"
echo "   gh auth login"
echo "   选择: GitHub.com → HTTPS → Yes → Login with a web browser"
echo ""
echo "3. 推送代码:"
echo "   git push -u origin main"
echo ""
echo ""
echo "=========================================="
echo "  当前状态"
echo "=========================================="
echo "本地仓库: $(pwd)"
echo "远程仓库: https://github.com/Haohao-end/openagent.git"
echo "当前分支: main"
echo "提交数量: $(git rev-list --count HEAD)"
echo "最新提交: $(git log -1 --oneline)"
echo ""
echo "✅ 准备就绪！请选择一种方式推送代码。"
echo ""
